{{- if or .Values.blue.enabled .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "password-generator.fullname" . }}-{{ if .Values.blue.enabled }}blue{{ else }}{{ if .Values.green.enabled }}green{{ end }}{{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "password-generator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      version: {{ if .Values.blue.enabled }}blue{{ else if .Values.green.enabled }}green{{ end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "password-generator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        version: {{ if .Values.blue.enabled }}blue{{ else if .Values.green.enabled }}green{{ end }}
    spec:
      serviceAccountName: {{ include "password-generator.serviceAccountName" . }}
      securityContext: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ if .Values.blue.enabled }}{{ .Values.blue.image.tag }}{{ else if .Values.green.enabled }}{{ .Values.green.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}