apiVersion: v1
kind: Service
metadata:
  name: {{ include "password-generator.fullname" . }}-{{ if .Values.blue.enabled }}blue{{ else if .Values.green.enabled }}green{{ end }}
  labels:
    app.kubernetes.io/name: {{ include "password-generator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "password-generator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    version: {{ if .Values.blue.enabled }}blue{{ else if .Values.green.enabled }}green{{ end }}
